/**
 * @param {string} authToken Autentication token generated by the server when verifying user during login section. 
 * @description Used in many scenarious when interacting with user object
 */
const authToken = localStorage.getItem("accessToken");
export default authToken;

/**
 * @param {string} Username Username for logged in user. First name and last name concatted with an underscore. Used in profileEndpoint variable
 */
export const username = localStorage.getItem("username");

/**
 * @param {string} avatar avatar for logged in user. Used f.ex to set avatar-image in header
 */
export const avatar = localStorage.getItem("avatar");